spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/duty_schedule_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

logging:
  level:
    ru.otus.notification: DEBUG