spring:
  application:
    name: duty-schedule-service
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/duty_schedule_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

server:
  port: 8080

logging:
  level:
    ru.otus.dutyschedule: DEBUG
    org.hibernate.SQL: DEBUG

#  flyway:
#    enabled: false
##    enabled: true
##    baseline-on-migrate: true