spring:
  application:
    name: duty-schedule-service
  datasource:
    url: jdbc:postgresql://localhost:5432/duty_schedule_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate    # только проверяет, не создаёт
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  shell:
    interactive:
      enabled: true

server:
  port: 8080

logging:
  level:
    ru.otus.dutyschedule: DEBUG
    org.hibernate.SQL: DEBUG