spring:
  application:
    name: security-service

  shell:
    interactive:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/security_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8081

security:
  jwt:
    lifetime: 300000 # ms
    public-key-path: classpath:keys/public.pem
    private-key-path: classpath:keys/private.pem