CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('CHIEF', 'EMPLOYEE')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    department_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    special BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    chief_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (chief_id) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS duty_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED')),
    created_by BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS duties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL,
    comment TEXT,
    special_duty BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(255) NOT NULL CHECK (status IN ('SCHEDULED', 'SUBSTITUTED', 'CANCELLED')),
    duty_group_id BIGINT,
    employee_id BIGINT,
    department_id BIGINT,
    substituted_by BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (duty_group_id) REFERENCES duty_groups(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (department_id) REFERENCES departments(id),
    FOREIGN KEY (substituted_by) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS absences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL CHECK (type IN ('SICK_LEAVE', 'VACATION', 'TIME_OFF')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255),
    employee_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

ALTER TABLE IF EXISTS employees ADD FOREIGN KEY (department_id) REFERENCES departments(id);