CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('CHIEF', 'EMPLOYEE')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    department_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id BIGINT NOT NULL,
    employee_email VARCHAR(255) NOT NULL,
    employee_full_name VARCHAR(255) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    type VARCHAR(50) NOT NULL,
    sent BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    special BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    chief_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (chief_id) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS duty_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED')),
    created_by BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS duties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL,
    comment TEXT,
    special_duty BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(255) NOT NULL CHECK (status IN ('SCHEDULED', 'SUBSTITUTED', 'CANCELLED')),
    duty_group_id BIGINT,
    employee_id BIGINT,
    department_id BIGINT,
    substituted_by BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (duty_group_id) REFERENCES duty_groups(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (department_id) REFERENCES departments(id),
    FOREIGN KEY (substituted_by) REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS absences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL CHECK (type IN ('SICK_LEAVE', 'VACATION', 'TIME_OFF')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255),
    employee_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

ALTER TABLE IF EXISTS employees ADD FOREIGN KEY (department_id) REFERENCES departments(id);

-- ============================================
-- 1. Создаём начальника
-- ============================================
INSERT INTO employees (full_name, email, password, role, active)
VALUES ('Петрова Анна Сергеевна', 'anna@company.ru', '123456', 'CHIEF', true);

-- ============================================
-- 2. Создаём отделы
-- ============================================

-- Особые отделы
INSERT INTO departments (name, special, active, chief_id)
VALUES ('Бухгалтерия', true, true, 1);

INSERT INTO departments (name, special, active, chief_id)
VALUES ('Казначейство', true, true, 1);

-- Обычные отделы
INSERT INTO departments (name, special, active, chief_id)
VALUES ('ИТ-отдел', false, true, 1);

INSERT INTO departments (name, special, active, chief_id)
VALUES ('HR-отдел', false, true, 1);

INSERT INTO departments (name, special, active, chief_id)
VALUES ('Хозяйственный отдел', false, true, 1);

-- ============================================
-- 3. Создаём сотрудников
-- ============================================

-- Бухгалтерия (особый) — 4 сотрудника
INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Иванова Мария Ивановна', 'ivanova@company.ru', '123456', 'EMPLOYEE', true, 1);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Смирнова Елена Петровна', 'smirnova@company.ru', '123456', 'EMPLOYEE', true, 1);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Козлова Ольга Викторовна', 'kozlova@company.ru', '123456', 'EMPLOYEE', true, 1);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Новикова Татьяна Андреевна', 'novikova@company.ru', '123456', 'EMPLOYEE', true, 1);

-- Казначейство (особый) — 3 сотрудника
INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Морозов Дмитрий Сергеевич', 'morozov@company.ru', '123456', 'EMPLOYEE', true, 2);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Волков Алексей Игоревич', 'volkov@company.ru', '123456', 'EMPLOYEE', true, 2);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Соколов Павел Николаевич', 'sokolov@company.ru', '123456', 'EMPLOYEE', true, 2);

-- ИТ-отдел (обычный) — 3 сотрудника
INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Кузнецов Артём Валерьевич', 'kuznetsov@company.ru', '123456', 'EMPLOYEE', true, 3);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Попов Максим Александрович', 'popov@company.ru', '123456', 'EMPLOYEE', true, 3);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Васильев Игорь Романович', 'vasiliev@company.ru', '123456', 'EMPLOYEE', true, 3);

-- HR-отдел (обычный) — 2 сотрудника
INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Михайлова Светлана Юрьевна', 'mihailova@company.ru', '123456', 'EMPLOYEE', true, 4);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Фёдорова Наталья Ильинична', 'fedorova@company.ru', '123456', 'EMPLOYEE', true, 4);

-- Хозяйственный отдел (обычный) — 2 сотрудника
INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Егоров Виктор Степанович', 'egorov@company.ru', '123456', 'EMPLOYEE', true, 5);

INSERT INTO employees (full_name, email, password, role, active, department_id)
VALUES ('Алексеев Сергей Владимирович', 'alekseev@company.ru', '123456', 'EMPLOYEE', true, 5);

-- ============================================
-- 4. Добавляем отсутствия
-- ============================================

INSERT INTO absences (employee_id, type, start_date, end_date, reason)
VALUES (2, 'SICK_LEAVE', '2026-03-10', '2026-03-14', 'ОРВИ');

INSERT INTO absences (employee_id, type, start_date, end_date, reason)
VALUES (6, 'VACATION', '2026-03-20', '2026-03-25', 'Ежегодный отпуск');